services:
  - type: web
    name: file-converter-engine
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: API_SECRET
        sync: false
